server:
  port: 9095
spring:
  application:
    name: adminpotal-service
logging:
  level:
    com:
      userservice: DEBUG
    root: INFO
#Eureka Configuration
#Eureka Client configuartion
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}

# Feign Client
feign:
  client:
    config:
      my-client:
        connectTimeout: 10000
        readTimeout: 300000


graphql:
  servlet:
    corsEnabled: true
